import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import localFont from "next/font/local";
import "./globals.css";
import LenisScrollProvider from "@/providers/lenisProvider";

const poppins = Poppins({
  weight: ['300','400','500','600','700','800'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

const horizona = localFont({
  src: [
    { path: "../fonts/ABCArizonaFlareVariable.ttf", weight: "400", style: "normal" },
    { path: "../fonts/ABCArizonaFlareVariable.ttf", weight: "500", style: "medium" },
    { path: "../fonts/ABCArizonaFlareVariable.ttf", weight: "700", style: "bold" },
    

  ],
  variable: "--font-horizona",
});

const sans = localFont({
  src: [
    { path: "../fonts/sans2.woff", weight: "400", style: "normal" },

 

  ],
  variable: "--font-sans",
});


export const metadata: Metadata = {
  title: "Hashmint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${poppins.variable}   
          ${horizona.variable}  
          ${sans.variable}    
          antialiased
        `}
      >
        <LenisScrollProvider>
          {children}
        </LenisScrollProvider>
      </body>
    </html>
  );
}
